name: CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Setup Yarn (Berry)
        uses: yarnpkg/action-setup@v3
        with:
          version: 'stable'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build